### ISSUE TITLE
research solar charging systems

### ISSUE THREAD

**Issue by daweim0** [Sea-Swindlers/Task-Board#32]
Using "maximum power point tracking" (MPPT) chips is a common solution, but seacharger got by without using one. I've seen other references to just using a buck converter instead. Either way, we have to make sure the solar panel output voltage doesn't go above our battery voltage

**Comment by snwu1996** [comment]
[Good comparison between MPPT charging options](https://www.cleanenergyreviews.info/blog/best-solar-charge-controllers)

[Good comparison between MPPT and PWM charge controllers](https://www.youtube.com/watch?v=kF_cVEYxj3E)
